### PR TITLE
include calendar name in ics export

### PR DESCRIPTION
**Pull request by amengsk**
ugly hack.
fixes https://github.com/yunity/karrot-frontend/issues/2452
lemme know if you see a better way!

### CODE REVIEW

**Review by nicksellen — APPROVED** [review]
It's definitely an improvement :+1: 

I wonder if it made sense to have the name as "<group>: <place>" when a place is specified? But fine either way.

I'm assuming clients that subscribe will update the name on the next fetch (once deployed..).

**Comment by amengsk** [comment]
you mean "group: place" instead of "place"?

**Comment by nicksellen** [comment]
> you mean "group: place" instead of "place"?

Exactly, but just an idea. I think either is an improvement.

**Comment by nicksellen** [comment]
I merged already, forgetting there was still an open question! But it's already an improvement, but feel free to make another PR if you think the other way is better ("group: place")

**Pull request merged**
